spring:
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
  datasource:
    url: jdbc:h2:file:/home/flaoliveira/db/health2gether/user
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

#  zipkin:
#    baseUrl: http://localhost:9411/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/