spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:user
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate.format_sql: true
#  zipkin:
#    baseUrl: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/